### PR TITLE
a11y support following WAI ARIA best practices, nested modals support and prettier format pre-commit hook.

### PR DESCRIPTION
**Pull request by xMokAx**
@AlexanderRichey I removed the `useCallback` because it shouldn't be used this way you can read about it here https://kentcdodds.com/blog/usememo-and-usecallback/. I want to know what case this line handles:
```js
Modal.styled = function(...args) {
  const styles =
    styled.div`
      ${css(...args)}
    ` || styled.div``;  // what is this for!? || styled.div``
  return function(props) {
    return <Modal WrapperComponent={styles} {...props} />;
  };
};
```

### CODE REVIEW

**Comment by xMokAx** [comment]
@AlexanderRichey  In the last commit:

- I added `react`, `react-dom` and `styled-components` back to devDependencies which I removed before because during development while I'm linking the local `styled-react-modal` to CRA to test the changes I make I thought they are the cause of `Invalid Hook Call Warning` error which is caused by `multiple instances of React` and the same error happens for `styled-components` as well. I could fix this error by making `styled-react-modal` uses the CRA's `react` and `styled-components` using the following commands inside the `styled-react-modal` directory:
`../../reactjs/useless-app/node_modules/react`
`../../reactjs/useless-app/node_modules/styled-components`
where `useless-app` directory is the app where I test the changes. I think `contribution.md` should be added to the project or at least contribution instructions in the `Readme.md`.
- Fixed the existing tests and right now I'm adding new tests to test a11y features and nested `modals`.

**Comment by AlexanderRichey** [comment]
Thanks for this PR. I'll take a look this weekend when I have some time. Thanks!

**Comment by xMokAx** [comment]
1- I tried to reduce the usage of `data-testid` as much as possible following this advice in [`dom-testing-library` docs](https://testing-library.com/docs/dom-testing-library/api-queries#bytestid):
In the spirit of the guiding principles, it is recommended to use this only after the other queries don't work for your use case. Using data-testid attributes do not resemble how your software is used and should be avoided if possible. That said, they are way better than querying based on DOM structure or styling css class names. Learn more about data-testids from the blog post "Making your UI tests resilient to change".
2- I noticed you are using `defaultProps`:
```js
Modal.defaultProps = {
  backgroundProps: {}
};
```
while I'm using `es6 default parameters`:
```js
function Modal({
  WrapperComponent,
  children,
  closeModal,
  closeOnBackgroundClick = false,
  onBackgroundClick,
  closeOnEscapeKeydown = true,
  onEscapeKeydown,
  allowScroll,
  beforeOpen,
  afterOpen,
  beforeClose,
  afterClose,
  backgroundProps,
  isOpen: isOpenProp,
  elToFocusAfterOpenId,
  elToFocusAfterCloseId,
  ...rest
})
```
We should use one or the other and i prefer `default parameters` as the component is a functional component.
What are your thoughts about those two issues?

**Comment by AlexanderRichey** [comment]
Thank you for taking the time to put this PR together. There's a few problems right now, but I'm happy to worth together to get this merged in and to add a11y support.

### Issues with this PR

- The PR needs to be rebased off develop. This should be easy. `git pull --rebase origin/develop`
- I think that the `closeModal`, `closeOnBackgroundClick`, and `closeOnEscapeKeydown` props are redundant. All of these cases can be handled with the existing `onBackgroundClick` and `onEscapeKeydown` props. I understand the desire to want to improve the most obvious and common use-case, but I don't think that this solution makes using the library any easier. If anything, I think that these additional props will confuse consumers of this library by making it unclear as to how the modal should be closed. The existing `onBackgroundClick` and `onEscapeKeydown` props cover the standard closing case in a straightforward way, as shown in the examples I gave. Additionally, we would have to require the `closeModal` prop in most cases, which would make the `<Modal />` component something in between a controlled an uncontrolled component. From the point of view of the consumer, I think it's best to keep the `<Modal />` component controlled. (I know it's not truly controlled since it has its own internal state, which is needed to handle animations, but from the point of view of the consumer of the library, it follows the controlled component pattern.)
- The new `elToFocusAfterOpenId` and `elToFocusAfterCloseId` props do not follow the standard paradigm of React. Passing element ids is fitting for a jquery library or for direct DOM manipulation. But it seems to go against the whole idea of React.
- Throwing bare error objects is dangerous and can cause one's entire app to crash. Right now, if I were to accept your changes, some consumers' apps might break. This is not acceptable for a little modal library to do. It would be better to use `console.warn` instead, I think.

### Idea for another approach

Another approach to adding a11y support, I think, would be to use [react-focus-lock](https://github.com/theKashey/react-focus-lock). You could simply wrap the [`content` that the modal renders](https://github.com/AlexanderRichey/styled-react-modal/blob/master/src/Modal.jsx#L134) in a `<FocusLock />`. Then, when the modal closes, you could have the consumer of the library put the focus back on something outside of the modal. You could also add the required `aria-modal` and `role="dialog"` attributes to the modal by default. You already do this in the `Modal.styled()` case, but, if we go this route, these attributes should be there in the bare `<Modal />` case too.

### Option to disable a11y?

I'm aware that some users of this library have used it to implement dropdowns, popovers, and other components as well. While the modal is the main use-case, I would prefer not to block these other uses. I think it would be a good idea to have a `disableA11y` prop, or something like it, that would remove the aria and role attributes and the focus trap, so that the library could still be used in other non-standard ways. We might also want a `disableFocusTrap` prop. These questions require some consideration, I think - what is the best possible API for an accessible modal with styled-components?

**Comment by xMokAx** [comment]
> Thank you for taking the time to put this PR together. There's a few problems right now, but I'm happy to worth together to get this merged in and to add a11y support.

You are welcome and I would be happier to work together. BTW here is an example I made before for accessible nested modals: https://repl.it/@xMokAx/accessible-nested-modals I used repl.it because focus doesn't work on codesandbox.io browser and i couldn't use a package from github on codepen.io.
> 
> ### Issues with this PR
> * The PR needs to be rebased off develop. This should be easy. `git pull --rebase origin/develop`

Consider it done.
> * I think that the `closeModal`, `closeOnBackgroundClick`, and `closeOnEscapeKeydown` props are redundant. All of these cases can be handled with the existing `onBackgroundClick` and `onEscapeKeydown` props. I understand the desire to want to improve the most obvious and common use-case, but I don't think that this solution makes using the library any easier. If anything, I think that these additional props will confuse consumers of this library by making it unclear as to how the modal should be closed. The existing `onBackgroundClick` and `onEscapeKeydown` props cover the standard closing case in a straightforward way, as shown in the examples I gave. Additionally, we would have to require the `closeModal` prop in most cases, which would make the `<Modal />` component something in between a controlled an uncontrolled component. From the point of view of the consumer, I think it's best to keep the `<Modal />` component controlled. (I know it's not truly controlled since it has its own internal state, which is needed to handle animations, but from the point of view of the consumer of the library, it follows the controlled component pattern.)

I required `closeModal` because I wanted to force a11y best practices in which the modal should be closed when Escape is pressed by default and of course callbacks (onEscapeKeydown, onBackgroundClick) are needed for other use cases.
> * The new `elToFocusAfterOpenId` and `elToFocusAfterCloseId` props do not follow the standard paradigm of React. Passing element ids is fitting for a jquery library or for direct DOM manipulation. But it seems to go against the whole idea of React.

We can use refs like so:
```js
// this should be done by the library user
const elToFocusAfterOpenRef = useRef(null)
// replace elToFocusAfterOpenId prop with elToFocusAfterOpenRef prop
elToFocusAfterOpenRef={elToFocusAfterOpenRef}
// inside the component
elToFocusAfterOpenRef.current.focus()
// instead of 
modalEl.current.querySelector(`#${elToFocusAfterOpenId}`).focus();
```
> * Throwing bare error objects is dangerous and can cause one's entire app to crash. Right now, if I were to accept your changes, some consumers' apps might break. This is not acceptable for a little modal library to do. It would be better to use `console.warn` instead, I think.

I just wanted to force users to apply a11y best practices in development but of course we can be less aggressive about that.
> 
> ### Idea for another approach
> Another approach to adding a11y support, I think, would be to use [react-focus-lock](https://github.com/theKashey/react-focus-lock). You could simply wrap the [`content` that the modal renders](https://github.com/AlexanderRichey/styled-react-modal/blob/master/src/Modal.jsx#L134) in a `<FocusLock />`. Then, when the modal closes, you could have the consumer of the library put the focus back on something outside of the modal. You could also add the required `aria-modal` and `role="dialog"` attributes to the modal by default. You already do this in the `Modal.styled()` case, but, if we go this route, these attributes should be there in the bare `<Modal />` case too.
> 

`react-focus-lock` looks great but its size minified and gzipped is 5 KBs while styled-react-modal itself is about only 2 KBs (I use https://bundlephobia.com/ to get the size of packages). I don't know if it's a good idea to increase the bundle size that much.
aria attributes are added to bare `<Modal />` children as well which is required to be a single element like a `div` for example. check line 184 in `Modal.jsx`:
```js
// this will throw error if children aren't a single react element
    React.Children.only(children);
    // add props to children element
    content = cloneElement(children, {
      ref: modalEl,
      role: "dialog",
      "aria-modal": true
    });
```
> ### Option to disable a11y?
> I'm aware that some users of this library have used it to implement dropdowns, popovers, and other components as well. While the modal is the main use-case, I would prefer not to block these other uses. I think it would be a good idea to have a `disableA11y` prop, or something like it, that would remove the aria and role attributes and the focus trap, so that the library could still be used in other non-standard ways. We might also want a `disableFocusTrap` prop. These questions require some consideration, I think - what is the best possible API for an accessible modal with styled-components?

We can have a prop like:
```js
isModal = true  //default true if false remove role="dialog" and aria-modal=true and disable the focus trap
// we can also add a separate prop to only disable focus trap
shouldTrapFocus = true  // default true if false disable the focus trap

**Comment by xMokAx** [comment]
In the current version of the component, I noticed that you are trying to prevent misfiring of callbacks but the problem is that the component is always mounted you can check that by adding this:
```js
useEffect(() => {
    console.log("mounted"); // this will run on mount
    return () => {
      console.log("unmounted"); // this will never run because the component is always mounted
    };
  }, []); // empty array will cause the effect to be called only on mount and on unmount
``` 
So in your solution which I had already tried before `afterOpen` will always be called twice which I think isn't your intention.
I handled this in a different way using state which works correctly and both `afterOpen` and `afterClose` are called only once but it needs some refactoring to be as following:
```js
const [wasOpen, setWasOpen] = useState(false);
  // Handle *after* isOpen change callbacks
  useEffect(() => {
    if (isOpen) {
      // to make sure it only runs if the modal was just opened
      if (!wasOpen) {
        if (modalEl.current) {
          modalTabbableChildren.current = tabbableChildren(modalEl.current);
          if (modalTabbableChildren.current.length === 0) {
            throw new Error(
              "Modal should always have at least one tabbable element. Maybe a button like Close, OK or Cancel."
            );
          }
          firstTabbableEl.current = modalTabbableChildren.current[0];
          lastTabbableEl.current =
            modalTabbableChildren.current[
              modalTabbableChildren.current.length - 1
            ];
          if (elToFocusAfterOpenId) {
            modalEl.current.querySelector(`#${elToFocusAfterOpenId}`).focus();
            // if the first tabbable element not in viewport because of the length of text
            // developer should give first paragraph tabindex=-1 to make it focusable
          } else if (!isInView(firstTabbableEl.current)) {
            firstFocusableEl.current = firstFocusableChild(modalEl.current);
            // if there is a focusable element focus it
            if (firstFocusableEl.current) {
              firstFocusableEl.current.focus();
              // if not throw an error
            } else {
              throw new Error(
                "The first tabbable element isn't in viewport. You can fix this by putting it in the top of the modal or give tabindex=-1 to the first paragraph in modal which will be automatically focused."
              );
            }
          } else {
            firstTabbableEl.current.focus();
          }
        }
        afterOpen && afterOpen();
        setWasOpen(true);
      }
    } else {
      // to make sure this will not run unless this modal was opened recently
      if (wasOpen) {
        if (elToFocusAfterCloseId) {
          document.querySelector(`#${elToFocusAfterCloseId}`).focus();
        } else {
          lastFocusedEl.current && lastFocusedEl.current.focus();
        }
        afterClose && afterClose();
        setWasOpen(false);
      }
    }
  }, [
    isOpen,
    afterOpen,
    wasOpen,
    afterClose,
    elToFocusAfterOpenId,
    elToFocusAfterCloseId
  ]);
```

**Comment by AlexanderRichey** [comment]
Hi @xMokAx -- Sorry for letting this linger for so long. I've been really busy the last few weeks and still have plans for coming week as well. I'm hoping to give some attention to this project after that. Just wanted to let you know that I haven't forgotten!

**Comment by xMokAx** [comment]
> Hi @xMokAx -- Sorry for letting this linger for so long. I've been really busy the last few weeks and still have plans for coming week as well. I'm hoping to give some attention to this project after that. Just wanted to let you know that I haven't forgotten!

Hi @AlexanderRichey : No worries, just message me when you have time to work on this project so we can agree on what we are going to do. Good luck.

**Comment by bplittle** [comment]
I'm super excited for this PR!

**Comment by bplittle** [comment]
Are there plans to integrate this in the near future?
Just wondering if we should wait on this PR or if our team should make our own changes to ensure ADA compliance when using this package.

**Comment by xMokAx** [comment]
> Are there plans to integrate this in the near future?
> Just wondering if we should wait on this PR or if our team should make our own changes to ensure ADA compliance when using this package.

It has been more than 2 months since I started this PR. I think we should make another package with the changes we need and I will be happy to contribute.

**Pull request closed without merging**
